Local IP-Address: 10.0.0.4
Static IP-Address: 20.25.38.131
Coin system loaded...
Requesting shared-playlist 404383...
Playlist 'smash' (ffa) downloaded; running...
BombSquad headless 1.4.150 (14369) entering server-mode Thu Jan 19 17:18:25 2023
UDP port 43210 access check successful. Your server appears to be joinable from the internet.
Added 1 kill entries.
ERROR: exception in Python call:
   root call: <unavailable>
   context: <UI Context>
   real-time: 68053
   game-time: <unavailable>
Traceback (most recent call last):
  File "data/scripts/bsUI.py", line 24788, in _filterChatMessage
    chatCmds.cmd(msg,clientID)
  File "data/scripts/chatCmds.py", line 1541, in cmd
    c.opt(clientID, msg)
  File "data/scripts/chatCmds.py", line 125, in opt
    bsInternal._chatMessage('The player ' + str(player.getName()) + ' is not yet registered')
UnicodeEncodeError: 'ascii' codec can't encode character u'\uf894' in position 0: ordinal not in range(128)
('WTF have', 0, 'icons in non-solo elim')
Added 2 kill entries.
Added 3 kill entries.
SendGamePacket() called before can_communicate set (bombsquad::ConnectionToClientUDP ptype 17)
Added 1 kill entries.
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
Added 7 kill entries.
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b6289c10>
   real-time: 408075
   game-time: 14384
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b6289c10>
   real-time: 408130
   game-time: 14400
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
Transaction successful
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
Added 10 kill entries.
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5128c50>
   real-time: 701683
   game-time: 14504
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5128c50>
   real-time: 701764
   game-time: 14528
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5128c50>
   real-time: 701932
   game-time: 14584
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5128c50>
   real-time: 702134
   game-time: 14648
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5128c50>
   real-time: 702509
   game-time: 14768
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
Transaction successful
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
Added 9 kill entries.
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b5238f50>
   real-time: 1139422
   game-time: 99048
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
Added 7 kill entries.
('WTF have', 0, 'icons in non-solo elim')
Added 9 kill entries.
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
Added 9 kill entries.
('WTF have', 0, 'icons in non-solo elim')
Added 10 kill entries.
('WTF have', 0, 'icons in non-solo elim')
('WTF have', 0, 'icons in non-solo elim')
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b4ff5050>
   real-time: 1688447
   game-time: 35624
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b4ff5050>
   real-time: 1688555
   game-time: 35656
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b4ff5050>
   real-time: 1688601
   game-time: 35672
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)
  File "data/scripts/bsSpaz.py", line 854, in handleMessage
    self.handleMessage(msg=msg)
TypeError: handleMessage() got an unexpected keyword argument 'msg'
ERROR: exception in Python call:
   root call: <unavailable>
   context: <smash.SuperSmash object at 0x7f11b4ff5050>
   real-time: 1688602
   game-time: 35672
Traceback (most recent call last):
  File "data/scripts/smash.py", line 273, in handleMessage
    super(self.__class__, self).handleMessage(m)
  File "data/scripts/bsSpaz.py", line 1935, in handleMessage
    Spaz.handleMessage(self, msg)

<max log size reached>
